M48
; DRILL file {KiCad (6.0.4)} date Mon Aug 22 18:12:24 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-22T18:12:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X3.1496Y-1.9685
X3.1496Y-5.8071
X8.6909Y-1.9685
X8.7106Y-5.8071
T0
M30
